myblog/about/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(
    '',
    url(r'^about$', 'about.views.aboutme', name="aboutme"),
    url(r'^about/pdf/$', 'about.views.export_classic', name="my_resume_pdf"),
    url(r'^about/(?P<resume_id>\d*)/$', 'curriculum.views.export_classic', name="resume_pdf"),
    url(r'^about/slide/$', 'about.views.get_resume', name="my_resume_slide"),
    url(r'^about/slide/(?P<resume_id>\d*)/$', 'curriculum.revealjs.views.get_resume', name="resume_slide"),
)

myblog/myapp/urls.py
from django.conf.urls import patterns, include, url
from myapp import views

urlpatterns = patterns('',
    url(r'^zinnia_tinymce/prism-form.html$', views.PrismFormView.as_view(), name="tinymce-prism-form")
)

myblog/mytools/urls.py
from django.conf.urls import patterns, url
from mytools import views


urlpatterns = patterns(
    'mytools',
    url('^$', views.home, name="home"),
)
for tool in views.TOOLS:
    tool_url = '%s/$' % tool.name
    urlpatterns += (
        url(tool_url, tool.as_view(), name=tool.name),
    )

myblog/urls.py
from django.conf import settings as s
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

from zinnia.sitemaps import TagSitemap
from zinnia.sitemaps import EntrySitemap
from zinnia.sitemaps import CategorySitemap

from sitemaps import WebsiteSitemap

sitemaps = {
    'tags': TagSitemap,
    'blog': EntrySitemap,
    'categories': CategorySitemap,
    'website': WebsiteSitemap,
}

urlpatterns = patterns(
    '',
    url(r'^$', RedirectView.as_view(url='/weblog/', permanent=True)),
    url(r'^photos$', 'photos.views.photos', name="photos"),
    url(r'^', include('about.urls')),
    url(r'^', include('myapp.urls')),
    url(r'^tools/', include('mytools.urls', namespace='mytools')),
    url(r'^bio/', include('bio.urls')),
    url(r'^bio/', include('bio.guide.urls')),
    url(r'^bio/', include('bio.items.urls')),
    url(r'^bio/', include('bio.scheduler.urls')),
    url(r'^bio/', include('schedule.urls')),
    url(r'^tinymce/zinnia/', include('zinnia_tinymce.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^weblog/', include('zinnia.urls', namespace='zinnia')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^xmlrpc/$', 'django_xmlrpc.views.handle_xmlrpc'),
)

urlpatterns += patterns(
    'django.contrib.sitemaps.views',
    url(r'^sitemap.xml$', 'index',
        {'sitemaps': sitemaps}),
    url(r'^sitemap-(?P<section>.+)\.xml$', 'sitemap',
        {'sitemaps': sitemaps}),
)

if s.DEBUG:
    urlpatterns += static(s.STATIC_URL, document_root=s.STATIC_ROOT)
    urlpatterns += static(s.MEDIA_URL, document_root=s.MEDIA_ROOT)

myblog/myadmin/models.py
from django.db import models

# Create your models here.

myblog/myapp/models.py
from django.db import models

# Create your models here.

myblog/mycomment/models.py
from django.db import models

# Create your models here.

myblog/mytools/models.py
from django.db import models

# Create your models here.

myblog/photos/models.py
from django.db import models

# Create your models here.

myblog/myadmin/forms.py
from django import forms
from zinnia.admin.forms import EntryAdminForm as BaseEntryAdminForm


class EntryAdminForm(BaseEntryAdminForm):
    pingback_enabled = forms.BooleanField(widget=forms.HiddenInput(), initial=0, required=False)
    trackback_enabled = forms.BooleanField(widget=forms.HiddenInput(), initial=0, required=False)

myblog/mycomment/forms.py
from django import forms
from django_comments.forms import CommentForm as BaseCommentForm
from captcha.fields import ReCaptchaField


class CommentForm(BaseCommentForm):
    captcha = ReCaptchaField()


class CommentAdminForm(BaseCommentForm):
    site = forms.BooleanField(widget=forms.HiddenInput(), required=False)
    is_public = forms.BooleanField(widget=forms.HiddenInput(), initial=1, required=False)

myblog/about/views.py
from django.shortcuts import render
from curriculum.models import Resume
from curriculum.views import export_classic as _export_classic
from curriculum.revealjs.views import get_resume as _get_resume


def aboutme(request):
    return render(request, 'about.html', {
        'title': 'About me',
        'resume': Resume.objects.get(pk=1)
    })


def export_classic(request):
    return _export_classic(request, 1)


def get_resume(request):
    return _get_resume(request, 1)

myblog/myadmin/views.py
from django.shortcuts import render

# Create your views here.

myblog/myapp/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from zinnia_tinymce.views import StaffMemberRequiredMixin


class PrismFormView(StaffMemberRequiredMixin,
                    TemplateView):
    template_name = 'zinnia_tinymce/prism-form.html'
    content_type = 'text/html'


def credits(request):
    return render(request, 'credits.html', {
        'title': 'Credits',
    })

myblog/mycomment/views.py
from django.shortcuts import render

# Create your views here.

myblog/mytools/views.py
import re
import json

import yaml
# from lxml import etree

from django.shortcuts import render
from django.views.generic import View
from django.core.urlresolvers import reverse_lazy as reverse
from django.core.cache import cache
from django.utils.six import BytesIO

from flickr_pony.storage import get_flickr_storage, FlickrError


def home(request):
    return render(request, 'mytools/home.html', {
        'tools': TOOLS,
    })


class ToolView(View):
    def _get_context(self):
        return {}

    def get_context(self):
        context = {'tool': self}
        context.update(self._get_context())
        return context

    def get(self, request):
        context = self.get_context()
        return render(request, self.template_name, context)

    def get_url(self):
        return reverse('mytools:' + self.name)


class FlickrIdView(ToolView):
    name = 'flickrid'
    verbose_name = 'Flickr ID'
    description = 'Get email from Flickr ID or reverse'
    template_name = 'mytools/flickr.html'

    def _get_id(self, email):
        storage = get_flickr_storage()
        try:
            id_ = storage.get_user_id(email)
            cache_key = 'flickr_id:%s' % email
            cache.set(cache_key, id_, 3600*6)
        except FlickrError as err:
            id_ = 'Error: %s' % str(err)
        return id_

    def get(self, request):
        context = self.get_context()
        if request.GET.get('q'):
            cache_key = 'flickr_id:%s' % request.GET['q']
            context['response'] = cache.get(cache_key) or self._get_id(request.GET['q'])
        return render(request, self.template_name, context)


class FormatValidatorView(ToolView):
    name = 'format_validator'
    verbose_name = 'Format validator'
    description = 'Valid differents format'
    template_name = 'mytools/format_validator.html'

    validators = {
        'JSON': json.loads,
        'YAML': yaml.load,
        # 'XML': lambda x: etree.parse(BytesIO(x)),
        'regexp': re.compile,
    }

    def get(self, request):
        context = self.get_context()
        context['format'] = request.GET.get('format')
        if request.GET.get('q'):
            validator = self.validators.get(request.GET.get('format'))
            if validator is None:
                response = 'Bad format!'
            else:
                try:
                    validator(request.GET['q'])
                    response = 'OK!'
                except Exception as err:
                    response = 'Error: %s' % str(err)
            context.update({
                'response': response,
                'q': request.GET['q'],
            })
        return render(request, self.template_name, context)


TOOLS = (
    FlickrIdView,
    FormatValidatorView,
)

myblog/photos/views.py
from django.shortcuts import render
from django.views.decorators.cache import cache_page
from flickr_pony.storage import get_flickr_storage


@cache_page(60*30)
def photos(request):
    storage = get_flickr_storage()
    if storage.user_id:
        photos = storage.list_all_size()
    else:
        photos = []
    return render(request, 'photos.html', {
        'title': "Photo gallery",
        'photos': photos,
    })

myblog/about/templates/about.html
{% extends "zinnia/base.html" %}
{% load i18n staticfiles %}

{% block title %}{{ title }}{% endblock title %}

{% block meta %}
<meta property="og:title" content="{{ title }}">
<meta property="og:type" content="profile">
<meta property="og:first_name" content="Anthony">
<meta property="og:last_name" content="Monthe">
<meta property="og:username" content="ZuluPro">
{% endblock meta %}

{% block link %}
  <link rel="stylesheet" href="{% static "css/animate.css" %}">
  <link rel="stylesheet" href="//lipis.github.io/flag-icon-css/css/flag-icon.css">
{% endblock link %}

{% block html-attrs %}ng-app="app"{% endblock html-attrs %}

{% block content %}
<section></section>
<section id="aboutme" class="aboutme">
<div class="pure-g">
  <div class='pure-u-1 pure-u-lg-1-2'>
   <div id="aboutme-column">
    <h2>About me</h2>
    <p><i>Hey, what's up! I'm Anthony, {{ resume.resume }}</i></p>
    <p>Or simply</p>
    <p><i>Opensource enthusiast who loves its works and skateboarding.</i></p>
    <p class="link-bar">
     <a href="mailto:{{ resume.email }}" target="blank"><i class="fa fa-send fa-3x"></i></a>
     <a href="http://stackoverflow.com/users/{{ resume.stackoverflow }}" target="blank"><i class="fa fa-stack-overflow fa-3x"></i></a>
     <a href="https://github.com/{{ resume.github }}" target="blank"><i class="fa fa-github fa-3x"></i></a>
     <a href="https://plus.google.com/u/0/{{ resume.google }}" target="blank"><i class="fa fa-google-plus fa-3x"></i></a>
     <a href="https://fr.linkedin.com/in/{{ resume.linkedin }}" target="blank"><i class="fa fa-linkedin fa-3x"></i></a>
     <!-- <a href="https://angel.co/{{ resume.angellist }}" target="blank"><i class="fa fa-angellist fa-3x"></i></a> -->
     <a href="https://www.flickr.com/photos/{{ resume.flickr }}/" target="blank"><i class="fa fa-flickr fa-3x"></i></a>
     <a href="skype:{{ resume.skype }}" target="blank"><i class="fa fa-skype fa-3x"></i></a>
    </p>
   </div>
  </div>
  <div class='pure-u-1 pure-u-lg-1-2'>
   <img class="pure-img" src="{% static "img/bigme.jpg" %}">
  </div>
</div>
</section>

<section id="training">
  <div class='pure-u-1-1'>
   <h1><center>Education & degree</center></h1>
   <ul id="formation">
    {% for certification in resume.certifications.all %}
    <li><div>{{ certification.start_year }}</div><div>{{ certification.certification.title }} at {{ certification.certification.authority }}</div></li>
    {% endfor %}
    {% for training in resume.trainings.all %}
    <li><div>{{ training.year }}</div><div>{{ training.degree }} in {{ training.topic }}</div></li>
    {% endfor %}
   </ul>
  </div>
</section>

<section class="project" id="project">
  <h1><center>Yes I'm contributing</center></h1>
  <div class='pure-g'>
    {% for project in resume.projects.all %}
      <div class='pure-u-1 pure-u-sm-1-2 pure-u-md-1-3 pure-u-lg-1-4 pure-u-xl-1-5'>
        <h4>
         <a href="{{ project.project.url }}"><i class="fa fa-link"></i></a>
         {{ project.project.title }}
        </h4>
        <p>{{ project.project.description }}</p>
      </div>
    {% endfor %}
  </div>
</section>

<section id="languages" class="i18n">
  <h1>I am i18n</h1>
  <div class='pure-g'>
    <div class='pure-u-1-4'>
      <h1><span class="flag-icon flag-icon-fr"></span></h1>
      <h4>Le <u>Français</u> est ma langue maternelle</h4>
    </div>
    <div class='pure-u-1-4'>
      <h1><span class="flag-icon flag-icon-gb"></span></h1>
      <h4>I also speak <u>English</u></h4>
    </div>
    <div class='pure-u-1-4'>
      <h1><span class="flag-icon flag-icon-pt"></span></h1>
      <h4>E eu tento falar <u>Português</u></h4>
    </div>
    <div class='pure-u-1-4'>
      <h1><img src="{% static "img/python-logo.ico" %}" height="35px" alt="Python"></h1>
      <h4><code>from django.utils import <u>six</u></code></h4>
    </div>
  </div>
  <br>
</section>

<section id="more" class="more">
  <h1><center>Get more about me</center></h1>
  <br>
  <div class='pure-g'>
    <div class='pure-u-1-3'>
      <a href="{% static "gpg.asc" %}">
        <i class="fa fa-lock fa-5x"></i>
      </a>
    </div>
    <div class='pure-u-1-3'>
      <a href="{% url "my_resume_pdf" %}">
        <i class="fa fa-file-pdf-o fa-5x"></i>
      </a>
    </div>
    <div class='pure-u-1-3'>
      <a href="{% url "my_resume_slide" %}">
        <img src="{{ resume.website_qrcode }}" width="90px">
      </a>
    </div>
  </div>
  <div class='pure-g'>
    <div class='pure-u-1-3'>
        <h4>Get my GPG key</h4>
    </div>
    <div class='pure-u-1-3'>
        <h4>Get my resume</h4>
    </div>
    <div class='pure-u-1-3'>
        <h4>See my resume slide</h4>
    </div>
  </div>
</section>

<section class="skills" id="skill-section">
 <div class="pure-g">
  <div class='pure-u-1-1' ng-controller="SkillListCtrl as skillList">
   <h1><center>Skills</center></h1>
   <div class="pure-form" ng-submit="skillList.filter()">
   <input id="skill-input" class="pure-input-1 pure-input-rounded" type="text" ng-model="skillList.q" placeholder="Filter by category or name">
   </div>
   <div>
    <div class="pure-g">
     <div class='pure-u-1-2 pure-u-sm-1-3 pure-u-md-1-4 pure-u-lg-1-5 pure-u-xl-1-6' ng-repeat="skill in skillList.filter()">
      <div class="wow pulse" data-wow-duration="{$ skill.rank - 6 $}s" data-wow-iteration="infinite" data-wow-offset="100" data-wow-delay="{$ 1000 / skill.rank  $}ms">
       <div class="wow {$ skillList.getAnimation(skill.rank) $} " data-wow-delay="{$ 1000 / skill.rank $}ms" data-wow-offset="100">
        <div class="wow rollIn " data-wow-delay="{$ 1000 / skill.rank $}ms" data-wow-offset="100">
         <p class="circle" style="background-color: {$ skill.color $};">
          <a href="{$ skill.url $}">{$ skill.name $}</a>
         </p>
        </div>
       </div>
      </div>
     </div>
    </div>
   </div>
 </div>
</section>
{% endblock content %}

{% block foot-script %}
<script src="{% static "prism/prism.js" %}"></script>
<script src="{% static "js/angularjs.js" %}"></script>
<script src="{% static "js/wow.js" %}"></script>
<script src="{% static "js/about.js" %}"></script>
{% endblock foot-script %}

myblog/myapp/templates/base/navbar.html
{% load i18n staticfiles %}
<div class="pure-g nav-container">
 <section>
 <div class="pure-u-1 pure-u-lg-1-3">
  <ul class="left">
   <li class="name">
    <a href="{% url 'aboutme' %}" title="Anthony Monthe" rel="home">
     <img src="/static/img/avatar.png" height="60" width="60" style="border-radius: 70px;">
     Anthony Monthe
    </a>
   </li>
  </ul>
 </div>

 <div class="pure-u-1 pure-u-lg-2-3 pure-menu pure-menu-horizontal">
  <ul class="right pure-menu-list">
   <li>
   <a href="{% url 'aboutme' %}" title="Anthony Monthe"><i class="fa fa-user"></i>{% trans "About me" %}</a>
   </li>
   <li><a href="{% url 'zinnia:entry_archive_index' %}" title="{% trans "My blog" %}"><i class="fa fa-sticky-note"></i>Blog</a></li>
   <li><a href="{% url 'photos' %}" title="{% trans "Photos" %}" class="feeds"><i class="fa fa-camera-retro"></i>{% trans "Photos" %}</a></li>
   <li class="pure-menu-item pure-menu-has-children pure-menu-allow-hover">
    <a class="pure-menu-link" href="{% url "mytools:home" %}" title="{% trans "Tools" %}"><i class="fa fa-wrench"></i>{% trans "Tools" %}</a>
    <ul class="pure-menu-children">
     {% for tool in tools %}
     <li class="pure-menu-item"><a href="{{ tool.get_url }}" class="pure-menu-link">{{ tool.verbose_name }}</a></li>
     {% endfor %}
    </ul>
   </li>
   {% if request.user.is_superuser %}
   <li><a href="{% url 'directories' %}" title="{% trans "Bio" %}" class="admin"><i class="fa fa-leaf"></i>{% trans "Bio" %}</a></li>
   <li><a href="{% url 'admin:index' %}" title="{% trans "Admin site" %}" class="admin"><i class="fa fa-edit"></i>{% trans "Admin" %}</a></li>
   {% endif %}
  </ul>
 </div>
 </section>
</div>

myblog/myapp/templates/bio/_plant_affinity.html
{% load i18n %}

<div class="pure-u-1-2 pure-sm-1-1 pure-lg-1-2">
 <h4>{% trans "Like" %}</h4>
 {% if plant.like.all.exists %}
  {% include "bio/_thumbnails.html" with objects=plant.like.all %}
 {% elif user.is_superuser %}
  <p>{% trans "No provided affinity" %}, <a href="{{ plant.get_admin_url }}#id_like"/>{% trans "Add it!" %}</a></p>
 {% else %}
  <p>{% trans "No provided affinity" %}.</p>
 {% endif %}
</div>

<div class="pure-u-1-2 pure-sm-1-1 pure-lg-1-2">
 <h4>{% trans "Dislike" %}</h4>
 {% if plant.dislike.all.exists %}
  {% include "bio/_thumbnails.html" with objects=plant.dislike.all %}
 {% elif user.is_superuser %}
 <p>{% trans "No provided affinity" %}, <a href="{{ plant.get_admin_url }}#id_like"/>{% trans "Add it!" %}</a></p>
 {% else %}
 <p>{% trans "No provided affinity" %}.</p>
 {% endif %}
</div>

myblog/myapp/templates/bio/_plant_pathology.html
{% load i18n %}

<h3>{% trans "Pathologies" %}</h3>
{% if plant.pathologies.exists %}
 {% include "bio/_thumbnails.html" with objects=plant.pathologies.all %}
{% elif user.is_superuser %}
 <p>{% trans "No provided pathology" %}, <a href="{{ plant.get_admin_url }}#id_pathologies"/>{% trans "Add it!" %}</a></p>
{% else %}
 <p>{% trans "No provided pathology" %}.</p>
{% endif %}

myblog/myapp/templates/bio/_plant_pest.html
{% load i18n %}

<h3>{% trans "Pests" %}</h3>
{% if plant.pests.exists %}
 {% include "bio/_thumbnails.html" with objects=plant.pests.all %}
{% elif user.is_superuser %}
 <p>{% trans "No provided pest" %}, <a href="{{ plant.get_admin_url }}#id_pests"/>{% trans "Add it!" %}</a></p>
{% else %}
 <p>{% trans "No provided pest" %}</p>
{% endif %}

myblog/myapp/templates/bio/_plant_rotation.html
{% load i18n %}

<div class="pure-u-1-2 pure-sm-1-2 pure-lg-1-2">
 <h4>{% trans "To plant before" %}</h4>
 {% if plant.before.all.exists %}
  {% include "bio/_thumbnails.html" with objects=plant.before.all %}
 {% else %}
  <p>{% trans "No provided plants" %}{% if user.is_staff %}, <a href="{{ plant.get_admin_url }}#id_before"/>{% trans "Add it!" %}</a>{% endif %}</p>
 {% endif %}
</div>

<div class="pure-u-1-2 pure-sm-1-2 pure-lg-1-2">
 <h4>{% trans "To plant after" %}</h4>
 {% if plant.after.all.exists %}
  {% include "bio/_thumbnails.html" with objects=plant.after.all %}
 {% else %}
 <p>{% trans "No provided affinity" %}{% if user.is_staff %}, <a href="{{ plant.get_admin_url }}#id_like"/>{% trans "Add it!" %}</a>{% endif %}</p>
 {% endif %}
</div>

myblog/myapp/templates/bio/_thumbnails.html
<div class="pure-g">
 {% for obj in objects %}
 <div class="pure-u-1-2 pure-u-sm-1-3 pure-u-md-1-6 pure-u-lg-1-8">
  <a href="{{ obj.get_absolute_url }}">
   {% if obj.illustration %}
   <img src="{{ obj.get_illustration_url }}" width="95%">
   {% endif %}
   <p>{{ obj }}</p>
  </a>
 </div>
 {% endfor %}
</div>

myblog/myapp/templates/bio/action.html
{% extends "zinnia/base.html" %}
{% load i18n %}

{% block title %}{% blocktrans %}Bio Calendar - {{ action }}{% endblocktrans %}{% endblock title %}

{% block content %}
<section class="body-head">
 <div class="content">
  <h2>
   <a href="{% url "directories" %}">{% trans "Bio directory" %}</a>
   / <a href="{% url "actions" %}">{% trans "Calendar" %}</a>
   / {{ action }}
  </h2>
 </div>
</section>

<section>
 <div class="content">
  {% if action.plants.exists %}
   <p><b>{% trans "Plants" %}</b>:</p>
   <ul>
    {% for plant in action.plants.all %}
    <li><a href="{{ plant.get_absolute_url }}">{{ plant }}</a></li>
    {% endfor %}
   </ul>
  {% endif %}

  {% if action.areas.exists %}
   <p><b>{% trans "Areas" %}</b>:</p>
   <ul>
    {% for area in action.areas.all %}
    <li><a href="{{ area.get_absolute_url }}">{{ area }}</a></li>
    {% endfor %}
   </ul>
  {% endif %}

  <p>{{ action.description }}</p>
 </div>
</section>
{% endblock content %}

myblog/myapp/templates/bio/actions.html
{% extends "zinnia/base.html" %}
{% load i18n %}

{% block title %}{% trans "Bio Calendar" %}{% endblock title %}

{% block content %}
<section class="body-head">
 <div class="content">
  <h2>
   <a href="{% url "directories" %}">{% trans "Bio directory" %}</a>
   / {% trans "Calendar" %}
  </h2>
 </div>
</section>

<section>
 <div class="content">
  <ul>
   {% for action in objects %}
   <li>{{ action.start|time:"H:i" }} <a href="{{ action.event.get_absolute_url }}">{{ action.title }}</li>
   {% endfor %}
  </ul>
  <p><a href="{% url "month_calendar" calendar_slug="bio" %}">{% trans "See full calendar" %}</a></p>
 </div>
</section>
{% endblock content %}

myblog/myapp/templates/bio/directories.html
{% extends "zinnia/base.html" %}
{% load i18n %}

{% block title %}{% trans "Bio directory" %}{% endblock title %}

{% block content %}
<section class="body-head">
 <div class="content">
  <h2>{% trans "Bio directory" %}</h2>
 </div>
</section>

<section class="thumbnails">
 <div class="content">
  <div class="pure-g">
   {% if user.is_superuser %}
    <div class="pure-u-1-2 pure-u-sm-1-2 pure-u-md-1-3 pure-u-lg-1-3">
     <h2><a href="{% url "plantitems" %}"><i class="fa fa-4x fa-list-ul" aria-hidden="true"></i><br>{% trans "Inventory" %}</a></h2>
    </div>
    <div class="pure-u-1-2 pure-u-sm-1-2 pure-u-md-1-3 pure-u-lg-1-3">
     <h2><a href="{% url "actions" %}"><i class="fa fa-4x fa-calendar" aria-hidden="true"></i><br>{% trans "Calendar" %}</a></h2>
    </div>
   {% endif %}
   <div class="pure-u-1-2 pure-u-sm-1-2 pure-u-md-1-3 pure-u-lg-1-3">
    <h2><a href="{% url "plants" %}"><i class="fa fa-4x fa-leaf" aria-hidden="true"></i><br>{% trans "Plants" %}</a></h2>
   </div>
   <div class="pure-u-1-2 pure-u-sm-1-2 pure-u-md-1-3 pure-u-lg-1-3">
    <h2><a href="{% url "pathologies" %}"><i class="fa fa-4x fa-medkit" aria-hidden="true"></i><br>{% trans "Pathologies" %}</a></h2>
   </div>
   <div class="pure-u-1-2 pure-u-sm-1-2 pure-u-md-1-3 pure-u-lg-1-3">
    <h2><a href="{% url "pests" %}"><i class="fa fa-4x fa-bug" aria-hidden="true"></i><br>{% trans "Pests" %}</a></h2>
   </div>
   <div class="pure-u-1-2 pure-u-sm-1-2 pure-u-md-1-3 pure-u-lg-1-3">
    <h2><a href="{% url "guides" %}"><i class="fa fa-4x fa-book" aria-hidden="true"></i><br>{% trans "Guide" %}</a></h2>
   </div>
  </div>
 </div>
</section>
{% endblock content %}

myblog/myapp/templates/zinnia/entries_similar.html
{% load i18n %}
<ul class="no-bullet">
  {% for entry in entries %}
  <li>
  </li>
  {% empty %}
  <li>
    {% trans "No similar entries." %}
  </li>
  {% endfor %}
</ul>

myblog/mytools/templates/mytools/flickr.html
{% extends "zinnia/base.html" %}
{% load i18n staticfiles %}

{% block title %}Flickr{% endblock title %}

{% block content %}
<section class="body-head">
 <div class="content">
   <h1><a href="{% url "mytools:home" %}">{% trans "Tools" %}</a> - {{ tool.verbose_name }}</h1>
 </div>
</section>
<section>
 <div class="content">
  <form method="get" class="pure-form">
   <fieldset class="pure-group">
    <input type="text" name="q" maxlength="100" class="pure-input-1" placeholder="{% trans "Enter here an email address or Flickr username" %}" value="{{ q }}">
   </fieldset>
   {% if response %}<p><b>{% trans "Response" %}</b>: {{ response }}</p>{% endif %}
   <input type="submit" name="submit" class="submit-post pure-button pure-button-primary" value="{% trans "Submit" %}">
  </form>
 </div>
</section>
{% endblock content %}

myblog/mytools/templates/mytools/format_validator.html
{% extends "zinnia/base.html" %}
{% load i18n staticfiles %}

{% block title %}Format validator{% endblock title %}

{% block content %}
<section class="body-head">
 <div class="content">
   <h1><a href="{% url "mytools:home" %}">{% trans "Tools" %}</a> - {{ tool.verbose_name }}</h1>
 </div>
</section>
<section>
 <div class="content">
  <form action="#textarea" class="pure-form">
   <fieldset class="pure-group">
    <textarea id="textarea" type="text" name="q" rows="20" class="pure-input-1" placeholder="{% trans "Enter here content that you want to valid" %}">{{ q }}</textarea>
    <select name="format" class="pure-input-1">
     {% for validator in tool.validators %}
      <option value="{{ validator }}"{% if format == validator%} selected{% endif %}>{{ validator }}</option>
     {% endfor %}
    </select>
   </fieldset>
   {% if response %}<p><b>{% trans "Response" %}</b>: {{ response }}</p>{% endif %}
   <input type="submit" name="submit" class="submit-post pure-button pure-button-primary" value="{% trans "Submit" %}">
  </form>
 </div>
</section>
{% endblock content %}